// Replays golden files generated by scripts/gen_golden_mechanics.py (CPython computed the
// expected values) and compares BIT PATTERNS, so a single ULP of drift anywhere in
// pyround2 / maker_quote / maker_fee / settle fails loud with the offending inputs.
//
// PMLAB_GOLDEN_DIR is compiled in by CMake when a python3 interpreter was found to generate
// the files; without one the suite skips (the pytest parity gate still covers parity).
#include <gtest/gtest.h>

#include <bit>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <limits>
#include <optional>
#include <sstream>
#include <string>

#include "pmlab_engine/mechanics.hpp"
#include "pmlab_engine/pyround.hpp"

namespace {

double parse_hex_double(const std::string& s) {
  if (s == "nan") return std::numeric_limits<double>::quiet_NaN();
  if (s == "inf") return std::numeric_limits<double>::infinity();
  if (s == "-inf") return -std::numeric_limits<double>::infinity();
  return std::strtod(s.c_str(), nullptr);
}

testing::AssertionResult BitEqual(double actual, double expected) {
  if (std::isnan(actual) && std::isnan(expected)) return testing::AssertionSuccess();
  if (std::bit_cast<std::uint64_t>(actual) == std::bit_cast<std::uint64_t>(expected)) {
    return testing::AssertionSuccess();
  }
  return testing::AssertionFailure()
         << "expected " << std::hexfloat << expected << " got " << actual << std::defaultfloat
         << " (" << expected << " vs " << actual << ")";
}

std::ifstream open_golden(const char* name) {
#ifdef PMLAB_GOLDEN_DIR
  return std::ifstream(std::string(PMLAB_GOLDEN_DIR) + "/" + name);
#else
  (void)name;
  return std::ifstream();  // not open -> caller skips
#endif
}

TEST(Golden, PyRound2) {
  std::ifstream in = open_golden("pyround2.txt");
  if (!in.is_open()) GTEST_SKIP() << "golden files not generated (no python3 at configure time)";
  std::string in_hex, out_hex;
  long n = 0;
  while (in >> in_hex >> out_hex) {
    const double x = parse_hex_double(in_hex);
    ASSERT_TRUE(BitEqual(pmlab::pyround2(x), parse_hex_double(out_hex)))
        << "pyround2(" << in_hex << ") at case " << n;
    ++n;
  }
  ASSERT_GT(n, 100000) << "golden file suspiciously small";
}

TEST(Golden, Mechanics) {
  std::ifstream in = open_golden("mechanics.txt");
  if (!in.is_open()) GTEST_SKIP() << "golden files not generated (no python3 at configure time)";
  std::string line;
  long n = 0;
  while (std::getline(in, line)) {
    std::istringstream ss(line);
    std::string kind;
    ss >> kind;
    if (kind == "quote") {
      std::string side_s, bid_s, ask_s, tick_s, want_s;
      ss >> side_s >> bid_s >> ask_s >> tick_s >> want_s;
      const auto side = side_s == "yes" ? pmlab::Side::kYes : pmlab::Side::kNo;
      const auto got = pmlab::maker_quote(side, parse_hex_double(bid_s), parse_hex_double(ask_s),
                                          parse_hex_double(tick_s));
      if (want_s == "none") {
        ASSERT_FALSE(got.has_value()) << line;
      } else {
        ASSERT_TRUE(got.has_value()) << line;
        ASSERT_TRUE(BitEqual(*got, parse_hex_double(want_s))) << line;
      }
    } else if (kind == "fee") {
      std::string p_s, c_s, want_s;
      int has = 0;
      ss >> p_s >> c_s >> has >> want_s;
      ASSERT_TRUE(BitEqual(pmlab::maker_fee(parse_hex_double(p_s), parse_hex_double(c_s), has != 0),
                           parse_hex_double(want_s)))
          << line;
    } else if (kind == "settle") {
      std::string side_s, f_s, fee_s, payout_s, stake_s, pnl_s;
      int y = 0;
      ss >> side_s >> f_s >> y >> fee_s >> payout_s >> stake_s >> pnl_s;
      const auto side = side_s == "yes" ? pmlab::Side::kYes : pmlab::Side::kNo;
      const auto got = pmlab::settle(side, parse_hex_double(f_s), y, parse_hex_double(fee_s));
      ASSERT_TRUE(BitEqual(got.payout, parse_hex_double(payout_s))) << line;
      ASSERT_TRUE(BitEqual(got.stake, parse_hex_double(stake_s))) << line;
      ASSERT_TRUE(BitEqual(got.pnl, parse_hex_double(pnl_s))) << line;
    } else {
      FAIL() << "unknown golden line: " << line;
    }
    ++n;
  }
  ASSERT_GT(n, 20000) << "golden file suspiciously small";
}

}  // namespace
